
<script>
/* ============================================================
   hey EU · Daten
   Kartenraster und Wortfilter stammen unverändert aus dem
   Spiel-Artefakt. Die Personen, Texte und Aufgaben sind für
   ältere Jugendliche neu geschrieben.
   ============================================================ */

const LAENDER = [
  { id:'is', name:'Island', flag:'🇮🇸', hauptstadt:'Reykjavík', hue:196,
    wz:'Geysir Strokkur', wzInfo:'Alle paar Minuten schießt hier eine Wasserfontäne 20 Meter hoch. Der Boden Islands sitzt auf zwei auseinanderdriftenden Erdplatten.',
    fakt:'Fast der gesamte Strom kommt aus Wasserkraft und Erdwärme — Island heizt buchstäblich mit dem Vulkan unter dem Haus.',
    person:{ name:'Elín', alter:17, ort:'Reykjavík', tags:['Geologie','Chor','Fotografie'],
      kurz:'Wohnt 20 Minuten von einem aktiven Vulkansystem entfernt und findet das völlig normal.',
      land:'Wir sind 380.000 Leute auf einer Insel so groß wie Ungarn. Man kennt entweder jeden oder niemanden.',
      alltag:'Schule bis halb drei, danach Schwimmhalle — draußen, beheizt, bei jedem Wetter. Das machen hier alle.',
      freizeit:'Ich fotografiere Langzeitbelichtungen von Nordlichtern. Im Winter hat man dafür ziemlich viel Zeit.',
      essen:'Skyr esse ich jeden Tag. Fermentierten Hai probierst du einmal und nie wieder, versprochen.' },
    quiz:{ f:'Woher bezieht Island fast seinen gesamten Strom?', r:'Wasserkraft und Erdwärme', w:['Kernkraft','Importe aus Norwegen'] } },

  { id:'ie', name:'Irland', flag:'🇮🇪', hauptstadt:'Dublin', hue:140,
    wz:'Cliffs of Moher', wzInfo:'214 Meter senkrecht in den Atlantik. Bei Sturm steht die Gischt so hoch, dass Regen von unten kommt.',
    fakt:'Irisch ist erste Amtssprache, aber nur eine Minderheit spricht es im Alltag — an der Schule lernen es trotzdem alle.',
    person:{ name:'Aoife', alter:16, ort:'Galway', tags:['Musik','Debattieren','Surfen'],
      kurz:'Spielt Fiddle in einer Session-Runde, in der sie mit Abstand die Jüngste ist.',
      land:'Der Westen ist leer und grün, Dublin ist voll und teuer. Ich mag den Westen.',
      alltag:'Wir haben ein Übergangsjahr zwischen Mittel- und Oberstufe — Praktika, Projekte, keine Noten. Ziemlich klug eigentlich.',
      freizeit:'Freitags Session im Pub, keine Noten auf Papier, alles nach Gehör. Und im Sommer Surfen, auch wenn das Wasser weh tut.',
      essen:'Brown Bread mit Butter. Klingt langweilig, ist es nicht.' },
    quiz:{ f:'Was ist in Irland das „Transition Year“?', r:'Ein notenfreies Jahr für Praktika und Projekte', w:['Ein Austauschjahr im Ausland','Das letzte Schuljahr vor dem Abschluss'] } },

  { id:'uk', name:'Großbritannien', flag:'🇬🇧', hauptstadt:'London', hue:220,
    wz:'Big Ben', wzInfo:'Big Ben ist streng genommen nur die Glocke; der Turm heißt Elizabeth Tower. Die Ganggenauigkeit wird mit aufgelegten Pennys justiert.',
    fakt:'Vier Landesteile, drei eigene Parlamente, ein gemeinsamer Pass — und seit 2020 kein EU-Mitglied mehr.',
    person:{ name:'Oliver', alter:17, ort:'Manchester', tags:['Politik','Fußball','Podcasts'],
      kurz:'Hat aus dem Brexit ein Schulprojekt gemacht und ist seitdem nicht mehr davon losgekommen.',
      land:'Wir sind raus aus der EU, und trotzdem hänge ich hier mit euch rum. Sagt vielleicht was aus.',
      alltag:'A-Levels heißt: drei Fächer, sonst nichts. Man entscheidet sich mit 16 ziemlich endgültig.',
      freizeit:'Ich mache einen Schulpodcast über Kommunalpolitik. Zwölf Hörer, aber sehr treue.',
      essen:'Sunday Roast bei meiner Nan. Nicht verhandelbar.' },
    quiz:{ f:'Was bezeichnet der Name „Big Ben“ genau genommen?', r:'Die Glocke im Turm', w:['Den Uhrturm','Das Parlamentsgebäude'] } },

  { id:'pt', name:'Portugal', flag:'🇵🇹', hauptstadt:'Lissabon', hue:35,
    wz:'Tram 28', wzInfo:'Die gelbe Straßenbahn klettert seit 1914 durch die Altstadt. Für Touristen eine Attraktion, für Anwohner der einzige Weg den Berg hoch.',
    fakt:'Portugal und Spanien trennt die älteste unveränderte Grenze Europas — festgelegt 1297.',
    person:{ name:'Tiago', alter:16, ort:'Porto', tags:['Surfen','Programmieren','Kochen'],
      kurz:'Steht dreimal die Woche vor der Schule im Wasser. Um sechs, wenn es noch dunkel ist.',
      land:'Alle denken, Portugal ist Lissabon. Porto ist besser, und das sagt hier jeder.',
      alltag:'Schule geht bis halb sechs. Dafür isst man mittags richtig, nicht so ein Brot zwischendurch.',
      freizeit:'Surfen, und ich baue eine App, die Wellenvorhersagen für meinen Strand zusammenrechnet.',
      essen:'Francesinha. Ein Sandwich, das dich für den Rest des Tages ausschaltet.' },
    quiz:{ f:'Was ist an der portugiesisch-spanischen Grenze besonders?', r:'Sie ist die älteste unveränderte Grenze Europas', w:['Sie verläuft komplett durch Gebirge','Sie wurde erst 1986 festgelegt'] } },

  { id:'es', name:'Spanien', flag:'🇪🇸', hauptstadt:'Madrid', hue:45,
    wz:'Sagrada Família', wzInfo:'Seit 1882 im Bau. Gaudí sagte, sein Auftraggeber habe es nicht eilig. Fertigstellung inzwischen für die 2030er angesetzt.',
    fakt:'Neben Spanisch sind Katalanisch, Galicisch und Baskisch regional Amtssprachen — Baskisch ist mit keiner anderen Sprache Europas verwandt.',
    person:{ name:'Lucía', alter:17, ort:'Valencia', tags:['Theater','Klima','Tanzen'],
      kurz:'Organisiert die Klimagruppe ihrer Schule und hat gelernt, wie zäh Verwaltung sein kann.',
      land:'Vier Sprachen, siebzehn Regionen, und jede findet ihre Version die richtige.',
      alltag:'Unterricht bis 14 Uhr, dann Mittagessen mit der Familie. Abends ist alles noch offen, wir essen um zehn.',
      freizeit:'Theater-AG. Und seit der Flut 2024 bin ich in einer Gruppe, die sich um Hochwasserschutz kümmert.',
      essen:'Paella am Sonntag, und zwar mit Kaninchen. Meeresfrüchte sind Touristenversion, sagt mein Vater.' },
    quiz:{ f:'Welche Sprache Spaniens ist mit keiner anderen europäischen Sprache verwandt?', r:'Baskisch', w:['Katalanisch','Galicisch'] } },

  { id:'fr', name:'Frankreich', flag:'🇫🇷', hauptstadt:'Paris', hue:225,
    wz:'Eiffelturm', wzInfo:'330 Meter, gebaut als Ausstellungsbau für 20 Jahre. Er blieb stehen, weil man oben Funkantennen anbringen konnte.',
    fakt:'Frankreich hat Gebiete auf fünf Kontinenten — deshalb reicht die EU-Außengrenze bis nach Südamerika.',
    person:{ name:'Chloé', alter:18, ort:'Lyon', tags:['Philosophie','Radsport','Kino'],
      kurz:'Schreibt gerade ihre Abiturklausur in Philosophie — vier Stunden, ein Satz als Thema.',
      land:'Wir diskutieren gern und laut. Das ist keine Streiterei, das ist Sport.',
      alltag:'Bac-Jahr. Philosophie ist Pflichtfach für alle, und die Prüfung ist ein einziger Aufsatz.',
      freizeit:'Rennrad. Und Kino im Originalton, davon gibt es hier zum Glück viel.',
      essen:'Mittags in der Kantine gibt es Vorspeise, Hauptgang, Käse und Nachtisch. Ich dachte, das sei überall so.' },
    quiz:{ f:'Warum blieb der Eiffelturm nach der Weltausstellung stehen?', r:'Er war als Funkturm nützlich', w:['Der Abriss war zu teuer','Ein Volksentscheid rettete ihn'] } },

  { id:'be', name:'Belgien', flag:'🇧🇪', hauptstadt:'Brüssel', hue:50,
    wz:'Atomium', wzInfo:'Ein Eisenkristall, 165 Milliarden Mal vergrößert. Gebaut für die Weltausstellung 1958 und eigentlich zum Abriss gedacht.',
    fakt:'In Brüssel sitzen Kommission und Rat der EU. Belgien selbst hat sechs Regierungen für elf Millionen Einwohner.',
    person:{ name:'Arthur', alter:16, ort:'Gent', tags:['Comics','Schach','Sprachen'],
      kurz:'Wechselt mitten im Satz zwischen Niederländisch, Französisch und Englisch, ohne es zu merken.',
      land:'Zwei Sprachgemeinschaften, die sich höflich ignorieren, und dazwischen die EU-Zentrale.',
      alltag:'Ich lerne Französisch als zweite Landessprache — und merke, dass die Leute in Wallonien trotzdem lieber Englisch mit mir reden.',
      freizeit:'Comics. Belgische natürlich, wir haben das Format hier erfunden.',
      essen:'Fritten aus der Bude, mit Mayo. Diese Diskussion führe ich nicht nochmal.' },
    quiz:{ f:'Was stellt das Atomium dar?', r:'Einen stark vergrößerten Eisenkristall', w:['Ein Modell des Sonnensystems','Ein Molekül aus der Chemieindustrie'] } },

  { id:'nl', name:'Niederlande', flag:'🇳🇱', hauptstadt:'Amsterdam', hue:28,
    wz:'Deltawerke', wzInfo:'Ein Sturmflutwehr-System, gebaut nach der Flutkatastrophe von 1953. Ein Viertel des Landes liegt unter dem Meeresspiegel.',
    fakt:'Es gibt mehr Fahrräder als Einwohner — und Radwege, die als eigenes Straßennetz geplant werden.',
    person:{ name:'Sanne', alter:17, ort:'Rotterdam', tags:['Architektur','Rudern','Debattieren'],
      kurz:'Kann dir genau erklären, warum ihr Wohnviertel drei Meter unter dem Meeresspiegel liegt.',
      land:'Wir haben das Land dem Wasser abgetrotzt und rechnen jedes Jahr nach, ob das noch aufgeht.',
      alltag:'Ich radle 11 Kilometer zur Schule. Bei Gegenwind ist das eine Charakterprüfung.',
      freizeit:'Rudern auf der Maas. Und ich schaue mir Neubauten an — Rotterdam wurde komplett neu gebaut, das sieht man.',
      essen:'Stroopwafel auf die Kaffeetasse legen, warten, essen. Es gibt keine bessere Methode.' },
    quiz:{ f:'Wofür wurden die Deltawerke gebaut?', r:'Als Schutz vor Sturmfluten', w:['Zur Stromerzeugung','Als Binnenhafen für Rotterdam'] } },

  { id:'de', name:'Deutschland', flag:'🇩🇪', hauptstadt:'Berlin', hue:210,
    wz:'Brandenburger Tor', wzInfo:'Von 1961 bis 1989 stand es im Sperrgebiet zwischen den beiden Mauern — erreichbar für niemanden.',
    fakt:'Neun Nachbarländer, mehr als jedes andere EU-Land. Schulpolitik machen dabei sechzehn Bundesländer einzeln.',
    person:{ name:'Ben', alter:17, ort:'Leipzig', tags:['Musik','Geschichte','Klettern'],
      kurz:'Wohnt in einer Stadt, die 1989 den Anfang gemacht hat, und hört davon jede Woche.',
      land:'Jedes Bundesland macht sein eigenes Abitur. Umziehen mitten in der Schulzeit ist ein Albtraum.',
      alltag:'Schule bis halb zwei, dann Bandprobe im Keller eines alten Umspannwerks.',
      freizeit:'Bass in einer Band, und klettern in der Halle. Draußen ist hier flach.',
      essen:'Bei uns gibt es Quarkkeulchen. Fragt niemand außerhalb Sachsens nach, aber sie sind großartig.' },
    quiz:{ f:'Wo lag das Brandenburger Tor zwischen 1961 und 1989?', r:'Im Sperrgebiet zwischen den Mauern', w:['Auf westlicher Seite','Direkt am Checkpoint Charlie'] } },

  { id:'dk', name:'Dänemark', flag:'🇩🇰', hauptstadt:'Kopenhagen', hue:355,
    wz:'Öresundbrücke', wzInfo:'Acht Kilometer Brücke, dann verschwindet die Strecke in einem Tunnel — damit die Flugzeuge von Kopenhagen starten können.',
    fakt:'Über 400 Inseln, aber nur etwa 70 sind bewohnt. Der höchste Punkt des Landes liegt bei 171 Metern.',
    person:{ name:'Freja', alter:16, ort:'Aarhus', tags:['Design','Handball','Ehrenamt'],
      kurz:'Verbringt ein Jahr an einer Efterskole — Internat, freiwillig, mitten in der Schulzeit.',
      land:'Flach, windig, gut organisiert. Und wir vertrauen einander erstaunlich weit.',
      alltag:'Efterskole heißt: ein Jahr mit Gleichaltrigen wohnen statt zu Hause. Fast jeder Zweite macht das.',
      freizeit:'Handball, und ich entwerfe Plakate für unsere Schulveranstaltungen.',
      essen:'Smørrebrød ist kein Snack, das ist eine Konstruktion. Reihenfolge der Beläge ist geregelt.' },
    quiz:{ f:'Warum geht die Öresundverbindung teilweise durch einen Tunnel?', r:'Wegen des Flugverkehrs am Kopenhagener Flughafen', w:['Wegen zu tiefen Wassers','Wegen der Schifffahrtsroute'] } },

  { id:'no', name:'Norwegen', flag:'🇳🇴', hauptstadt:'Oslo', hue:200,
    wz:'Geirangerfjord', wzInfo:'Ein Fjord ist ein vom Gletscher ausgeschürftes Tal, das das Meer geflutet hat. Norwegens Küste ist deshalb über 25.000 Kilometer lang.',
    fakt:'Norwegen ist kein EU-Mitglied, aber über den EWR an fast alle Binnenmarktregeln gebunden.',
    person:{ name:'Magnus', alter:18, ort:'Bergen', tags:['Ski','Umwelt','Elektronik'],
      kurz:'Diskutiert regelmäßig darüber, wie ein Ölstaat gleichzeitig Klimavorreiter sein will.',
      land:'Wir sind nicht in der EU, halten uns aber an fast alles. Das erklärt sich schlecht in einem Satz.',
      alltag:'In Bergen regnet es an 240 Tagen im Jahr. Man geht trotzdem raus, es gibt keine Alternative.',
      freizeit:'Langlauf, sobald Schnee liegt. Und ich löte an einem Wetterballon-Projekt der Schule.',
      essen:'Brunost — brauner Karamellkäse. Sieht falsch aus, schmeckt richtig.' },
    quiz:{ f:'In welcher Beziehung steht Norwegen zur EU?', r:'Kein Mitglied, aber über den EWR eng gebunden', w:['Vollmitglied seit 1995','Beitrittskandidat'] } },

  { id:'se', name:'Schweden', flag:'🇸🇪', hauptstadt:'Stockholm', hue:190,
    wz:'Vasa-Museum', wzInfo:'Ein Kriegsschiff, das 1628 nach 1300 Metern Fahrt sank und 333 Jahre später fast vollständig gehoben wurde.',
    fakt:'Das Allemansrätten erlaubt jedem, überall in der Natur zu wandern und zu zelten — auch auf privatem Grund.',
    person:{ name:'Elsa', alter:17, ort:'Göteborg', tags:['Film','Nachhaltigkeit','Chor'],
      kurz:'Schneidet Kurzfilme und schläft im Sommer regelmäßig irgendwo im Wald, ganz legal.',
      land:'Man darf hier überall zelten, auch auf fremdem Land. Das erklärt viel über uns.',
      alltag:'Wir duzen die Lehrkräfte mit Vornamen. Als eine Austauschschülerin „Frau Andersson“ sagte, wusste niemand, wer gemeint war.',
      freizeit:'Film-AG, und im Sommer Kanu mit Zelt. Fika ist keine Pause, das ist ein Termin.',
      essen:'Zimtschnecken. Es gibt sogar einen offiziellen Tag dafür, den 4. Oktober.' },
    quiz:{ f:'Was regelt das schwedische „Allemansrätten“?', r:'Das Recht, sich frei in der Natur zu bewegen', w:['Die Wehrpflicht','Das Wahlrecht ab 16'] } },

  { id:'fi', name:'Finnland', flag:'🇫🇮', hauptstadt:'Helsinki', hue:175,
    wz:'Lappland', wzInfo:'Nördlich des Polarkreises geht die Sonne im Sommer wochenlang nicht unter und im Winter wochenlang nicht auf.',
    fakt:'Finnisch ist mit Schwedisch oder Russisch nicht verwandt — es gehört zur finno-ugrischen Familie, wie Estnisch und Ungarisch.',
    person:{ name:'Aino', alter:16, ort:'Tampere', tags:['Physik','Sauna','Metal'],
      kurz:'Hat in der Schule kaum Hausaufgaben und findet die deutschen Erzählungen darüber beunruhigend.',
      land:'188.000 Seen und eine Sprache, die niemand von außen versteht. Wir mögen das so.',
      alltag:'Wir haben wenig Hausaufgaben und keine Schuluniform, dafür Mittagessen umsonst für alle. Seit den 40ern.',
      freizeit:'Sauna, dann in den See, auch im Februar. Und ich spiele Schlagzeug, hier hat jede zweite Kleinstadt eine Metalband.',
      essen:'Korvapuusti, also Zimtschnecken mit Kardamom. Und Lakritz, das salzig ist. Ja, salzig.' },
    quiz:{ f:'Mit welcher Sprache ist Finnisch verwandt?', r:'Estnisch', w:['Schwedisch','Russisch'] } },

  { id:'ee', name:'Estland', flag:'🇪🇪', hauptstadt:'Tallinn', hue:165,
    wz:'Altstadt von Tallinn', wzInfo:'Eine der besterhaltenen mittelalterlichen Städte Nordeuropas — Stadtmauer, Türme und Straßenverlauf stammen aus dem 14. Jahrhundert.',
    fakt:'Fast alle Verwaltungsleistungen laufen digital: Steuererklärung in Minuten, Wählen per Internet seit 2005.',
    person:{ name:'Kertu', alter:17, ort:'Tartu', tags:['Informatik','Chor','Politik'],
      kurz:'Hat ihre erste Steuererklärung in vier Minuten am Handy gemacht und versteht das Staunen nicht.',
      land:'Wir sind 1,3 Millionen Leute und haben den Staat quasi als App gebaut.',
      alltag:'Programmieren ist ab der Grundschule Teil des Unterrichts. Nicht als AG, als Fach.',
      freizeit:'Chor. Alle fünf Jahre singen 30.000 Menschen gemeinsam beim Sängerfest — das hat uns mit zur Unabhängigkeit gesungen.',
      essen:'Schwarzbrot. Estnisches Schwarzbrot, nicht das, was ihr dafür haltet.' },
    quiz:{ f:'Was ist in Estland seit 2005 landesweit möglich?', r:'Wählen über das Internet', w:['Schulpflicht bis 20','Kostenloser Nahverkehr im ganzen Land'] } },

  { id:'lv', name:'Lettland', flag:'🇱🇻', hauptstadt:'Riga', hue:350,
    wz:'Jugendstilviertel Riga', wzInfo:'Rund ein Drittel der Rigaer Innenstadt ist im Jugendstil gebaut — die größte zusammenhängende Sammlung Europas.',
    fakt:'Über die Hälfte der Landesfläche ist Wald, und der Anteil wächst seit Jahrzehnten.',
    person:{ name:'Līga', alter:16, ort:'Riga', tags:['Kunstgeschichte','Basketball','Imkern'],
      kurz:'Führt Austauschgruppen durch die Jugendstilstraßen und zeigt dabei immer dasselbe Lieblingshaus.',
      land:'Zwischen Ostsee und Wald, mit einer Hauptstadt voller verzierter Fassaden.',
      alltag:'Wir haben Schuluniform an vielen Schulen, aber jede Schule entwirft ihre eigene.',
      freizeit:'Basketball, und meine Großmutter bringt mir das Imkern bei. Der Honig kommt aus dem Wald hinterm Haus.',
      essen:'Rupjmaize, also Roggenbrot, und Kefir dazu. Klingt karg, ist es nicht.' },
    quiz:{ f:'Wofür ist die Rigaer Innenstadt bekannt?', r:'Die größte Jugendstil-Sammlung Europas', w:['Die älteste Universität des Baltikums','Einen mittelalterlichen Hafenkran'] } },

  { id:'lt', name:'Litauen', flag:'🇱🇹', hauptstadt:'Vilnius', hue:110,
    wz:'Berg der Kreuze', wzInfo:'Ein Hügel mit über 100.000 Kreuzen. In der Sowjetzeit dreimal planiert — und jedes Mal über Nacht neu bestückt.',
    fakt:'Litauisch gilt als die konservativste lebende indoeuropäische Sprache — es hat Formen bewahrt, die sonst nur aus dem Sanskrit bekannt sind.',
    person:{ name:'Matas', alter:17, ort:'Kaunas', tags:['Basketball','Geschichte','Sneaker'],
      kurz:'Erklärt dir binnen einer Minute, warum Basketball hier keine Sportart, sondern eine Konfession ist.',
      land:'Wir liegen ungefähr in der geografischen Mitte Europas und wurden trotzdem lange übersehen.',
      alltag:'Nach der Schule Training. Wer nicht spielt, schaut zu — die Liga füllt hier Hallen wie anderswo Fußball.',
      freizeit:'Basketball, und ich sammle Geschichten über den Berg der Kreuze von Leuten, die dabei waren.',
      essen:'Cepelinai. Sehr schwer, sehr gut, danach brauchst du eine Pause.' },
    quiz:{ f:'Was geschah in der Sowjetzeit mehrfach mit dem Berg der Kreuze?', r:'Er wurde planiert und neu errichtet', w:['Er wurde zum Museum erklärt','Er wurde ins Ausland verlegt'] } },

  { id:'pl', name:'Polen', flag:'🇵🇱', hauptstadt:'Warschau', hue:5,
    wz:'Altstadt von Warschau', wzInfo:'1944 fast vollständig zerstört, danach nach alten Gemälden originalgetreu wiederaufgebaut — heute UNESCO-Welterbe genau dafür.',
    fakt:'Polen hat die Ostgrenze der EU zu Belarus und der Ukraine und ist seit 2022 wichtigstes Transitland für Hilfslieferungen.',
    person:{ name:'Zuzanna', alter:18, ort:'Krakau', tags:['Journalismus','Schach','Wandern'],
      kurz:'Schreibt für die Schülerzeitung über Leute, die 2022 spontan Wohnungen geöffnet haben.',
      land:'Wir haben unsere Hauptstadt nach dem Krieg aus Gemälden rekonstruiert. Das sagt einiges über Sturheit.',
      alltag:'Matura im Frühjahr. Danach wollen viele weg — und ziemlich viele kommen inzwischen auch wieder.',
      freizeit:'Ich wandere in der Tatra und schreibe für unsere Schulzeitung.',
      essen:'Pierogi ruskie, mit Kartoffeln und Quark. Alles andere ist Nebensache.' },
    quiz:{ f:'Warum ist Warschaus Altstadt UNESCO-Welterbe?', r:'Wegen des originalgetreuen Wiederaufbaus nach 1945', w:['Weil sie den Krieg unbeschädigt überstand','Wegen ihrer barocken Stadtmauer'] } },

  { id:'cz', name:'Tschechien', flag:'🇨🇿', hauptstadt:'Prag', hue:15,
    wz:'Karlsbrücke', wzInfo:'1357 begonnen, angeblich am 9. Juli um 5:31 Uhr — die Zahlenfolge 1357 9/7 5:31 liest sich vorwärts wie rückwärts.',
    fakt:'Tschechien hat den höchsten Bierkonsum pro Kopf weltweit — und eine Brauereischule mit Abitur.',
    person:{ name:'Eliška', alter:16, ort:'Brünn', tags:['Chemie','Eishockey','Zeichnen'],
      kurz:'Zeichnet Comics über ihre Chemie-Olympiade-Gruppe und trifft den Ton dabei ziemlich genau.',
      land:'Ein Land ohne Meer, dafür mit einer Hauptstadt, die alle sehen wollen. Wir wohnen woanders.',
      alltag:'Gymnasium mit acht Jahren, Aufnahmeprüfung mit elf. Da wird früh sortiert.',
      freizeit:'Eishockey schauen, Chemie-Olympiade machen, Comics zeichnen. In der Reihenfolge.',
      essen:'Svíčková. Rindfleisch in Rahmsoße mit Knödeln, und ja, mit Preiselbeeren und Sahne.' },
    quiz:{ f:'Was ist am Baubeginn der Karlsbrücke bemerkenswert?', r:'Die Datumszahlen bilden ein Palindrom', w:['Sie wurde in einem Jahr fertig','Sie wurde von Karl IV. selbst entworfen'] } },

  { id:'at', name:'Österreich', flag:'🇦🇹', hauptstadt:'Wien', hue:340,
    wz:'Wiener Riesenrad', wzInfo:'Seit 1897 in Betrieb. Von ursprünglich 30 Waggons blieben nach dem Krieg 15 — aus Materialmangel wurde nur die Hälfte ersetzt.',
    fakt:'Österreich ist neutral: kein NATO-Mitglied, aber seit 1995 in der EU.',
    person:{ name:'Felix', alter:17, ort:'Graz', tags:['Musik','Bergsteigen','Kabarett'],
      kurz:'Spielt Klarinette im Landesjugendorchester und macht sich über den Begriff „Landesjugendorchester“ lustig.',
      land:'Zwei Drittel Alpen, ein Drittel Verwaltung. Und alles davon sehr ernst genommen.',
      alltag:'Zentralmatura, also einheitliche Prüfungen im ganzen Land. Vorher war das Glückssache.',
      freizeit:'Orchester, und im Sommer Klettersteige. Wien mag ich, aber alle drei Monate reicht.',
      essen:'Kaiserschmarrn nach dem Wandern. Vorher wäre unklug.' },
    quiz:{ f:'Welchen Status hat Österreich sicherheitspolitisch?', r:'Neutral, kein NATO-Mitglied', w:['NATO-Gründungsmitglied','NATO-Beitritt 1995'] } },

  { id:'ch', name:'Schweiz', flag:'🇨🇭', hauptstadt:'Bern', hue:0,
    wz:'Matterhorn', wzInfo:'4478 Meter, und die markante Pyramidenform entstand, weil vier Gletscher den Berg von allen Seiten gleichzeitig abgeschliffen haben.',
    fakt:'Vier Amtssprachen, kein EU-Mitglied, und über Sachfragen wird viermal im Jahr per Volksabstimmung entschieden.',
    person:{ name:'Luca', alter:17, ort:'Luzern', tags:['Politik','Snowboard','Uhren'],
      kurz:'Darf noch nicht wählen, verfolgt aber jede Abstimmungsvorlage, als hinge sein Leben davon ab.',
      land:'Wir stimmen über fast alles ab. Manchmal über Dinge, bei denen ich mir denke: wirklich, darüber?',
      alltag:'Viele machen eine Lehre statt Abitur, und das ist kein Abstieg. Mein Bruder repariert Turbinen und verdient mehr als ich je werde.',
      freizeit:'Snowboard im Winter, und ich schraube an alten Uhrwerken herum.',
      essen:'Fondue, aber nur ab Oktober. Es gibt Regeln.' },
    quiz:{ f:'Wie oft finden in der Schweiz landesweite Volksabstimmungen statt?', r:'Etwa viermal im Jahr', w:['Alle vier Jahre','Nur bei Verfassungsänderungen'] } },

  { id:'it', name:'Italien', flag:'🇮🇹', hauptstadt:'Rom', hue:120,
    wz:'Kolosseum', wzInfo:'Fasste bis zu 50.000 Zuschauer und hatte ein Sonnensegel, das Matrosen der Kriegsflotte über die Ränge spannten.',
    fakt:'In Italien stehen mehr UNESCO-Welterbestätten als in jedem anderen Land der Welt.',
    person:{ name:'Marco', alter:16, ort:'Bologna', tags:['Kochen','Fußball','Latein'],
      kurz:'Kocht seit er zehn ist für die ganze Familie und hat starke Meinungen über Nudelformen.',
      land:'Der Norden und der Süden führen seit 160 Jahren dasselbe Gespräch. Es wird nicht kürzer.',
      alltag:'Liceo classico heißt: fünf Jahre Latein und Altgriechisch. Ich frage mich täglich, warum, und würde es wieder machen.',
      freizeit:'Fußball auf der Piazza, bis es dunkel wird. Und kochen — richtig, nicht aus der Packung.',
      essen:'Tagliatelle al ragù. Nicht Spaghetti Bolognese, das gibt es hier nicht. Wirklich nicht.' },
    quiz:{ f:'Wer bediente im Kolosseum das Sonnensegel?', r:'Matrosen der römischen Flotte', w:['Sklaven aus der Arena','Die Zuschauer der obersten Ränge'] } },

  { id:'hu', name:'Ungarn', flag:'🇭🇺', hauptstadt:'Budapest', hue:60,
    wz:'Széchenyi-Bad', wzInfo:'Gespeist aus einer 1246 Meter tiefen Thermalquelle mit 74 Grad heißem Wasser. Budapest hat über hundert Thermalquellen im Stadtgebiet.',
    fakt:'Ungarisch ist keine indogermanische Sprache — die nächsten Verwandten sind Finnisch und Estnisch, und selbst die sind weit weg.',
    person:{ name:'Bence', alter:17, ort:'Szeged', tags:['Schwimmen','Mathe','Fotografie'],
      kurz:'Trainiert sechsmal die Woche im Becken und macht nebenbei Mathe-Wettbewerbe.',
      land:'Eine Sprache, die sonst niemand spricht, und Bäder, in denen alte Männer im Wasser Schach spielen.',
      alltag:'Wir haben Mathe-Wettbewerbe, die hier ernster genommen werden als Sport. Bei mir zufällig beides.',
      freizeit:'Schwimmen. Und Fotografie, meistens im Bad, wenn der Dampf richtig steht.',
      essen:'Gulyás ist bei uns eine Suppe, kein Eintopf. Das ist der häufigste Irrtum über uns.' },
    quiz:{ f:'Mit welchen Sprachen ist Ungarisch entfernt verwandt?', r:'Finnisch und Estnisch', w:['Rumänisch und Italienisch','Tschechisch und Slowakisch'] } },

  { id:'hr', name:'Kroatien', flag:'🇭🇷', hauptstadt:'Zagreb', hue:185,
    wz:'Stadtmauer von Dubrovnik', wzInfo:'Zwei Kilometer begehbare Mauer, bis zu sechs Meter dick. Dubrovnik war jahrhundertelang eine eigenständige Seerepublik.',
    fakt:'Kroatien hat 1244 Inseln und Felsen, aber nur knapp 50 sind bewohnt. Seit 2023 gilt hier der Euro.',
    person:{ name:'Petra', alter:16, ort:'Split', tags:['Meeresbiologie','Wasserball','Gitarre'],
      kurz:'Zählt in den Sommerferien Seegraswiesen für ein Forschungsprojekt und taucht dafür jeden Tag.',
      land:'Eine sehr lange Küste, sehr viele Inseln und im Sommer sehr viele Gäste.',
      alltag:'Im Sommer arbeiten fast alle in meinem Alter im Tourismus. Ich zähle lieber Seegras.',
      freizeit:'Wasserball, und Tauchen für ein Projekt der Uni Split. Gitarre abends am Hafen.',
      essen:'Peka — Fleisch und Gemüse unter einer Eisenglocke in der Glut. Dauert drei Stunden.' },
    quiz:{ f:'Was war Dubrovnik jahrhundertelang?', r:'Eine eigenständige Seerepublik', w:['Venezianische Provinz','Osmanische Hafenstadt'] } },

  { id:'gr', name:'Griechenland', flag:'🇬🇷', hauptstadt:'Athen', hue:205,
    wz:'Akropolis', wzInfo:'Der Parthenon hat fast keine geraden Linien: Säulen neigen sich leicht nach innen, der Sockel wölbt sich — damit er dem Auge gerade erscheint.',
    fakt:'Griechenland hat rund 6.000 Inseln, von denen etwa 200 bewohnt sind, und die längste Küste der EU.',
    person:{ name:'Nikos', alter:18, ort:'Thessaloniki', tags:['Archäologie','Segeln','Rap'],
      kurz:'Gräbt in den Sommerferien mit einem Uni-Team und findet dabei meistens Scherben.',
      land:'Alle kommen wegen der Antike. Wir leben aber im Jetzt, und das ist auch interessant.',
      alltag:'Nach der Schule Frontistirio, also Nachhilfeschule. Fast alle machen das, wegen der Uni-Aufnahmeprüfung.',
      freizeit:'Segeln, und ich schreibe Rap auf Griechisch. Die Sprache hat dafür erstaunlich gute Reime.',
      essen:'Bougatsa am Morgen, direkt aus dem Blech. Fragt nach der herzhaften Version.' },
    quiz:{ f:'Was ist am Bau des Parthenon ungewöhnlich?', r:'Er hat kaum gerade Linien — eine optische Korrektur', w:['Er besteht vollständig aus Marmorblöcken ohne Mörtel','Er wurde in nur zwei Jahren errichtet'] } },

  { id:'ro', name:'Rumänien', flag:'🇷🇴', hauptstadt:'Bukarest', hue:95,
    wz:'Karpaten', wzInfo:'In den rumänischen Karpaten lebt etwa die Hälfte aller Braunbären der EU — rund 6.000 Tiere.',
    fakt:'Rumänisch ist eine romanische Sprache, umgeben von slawischen und ungarischen Nachbarn.',
    person:{ name:'Ioana', alter:17, ort:'Cluj', tags:['Informatik','Wandern','Volkstanz'],
      kurz:'Programmiert für einen Wettbewerb und tanzt am Wochenende in einer Volkstanzgruppe. Beides ernsthaft.',
      land:'Wir sprechen eine romanische Sprache und niemand rechnet damit. Latein hilft hier wirklich.',
      alltag:'Cluj ist voller IT-Firmen, und in der Schule merkt man das. Halbe Klasse will programmieren.',
      freizeit:'Wandern in den Karpaten — mit Abstand zu den Bären. Und Volkstanz, seit ich sechs bin.',
      essen:'Sarmale, gefüllte Krautwickel, dazu Mămăligă. An Feiertagen gibt es nichts anderes.' },
    quiz:{ f:'Was ist sprachlich an Rumänien besonders?', r:'Es spricht eine romanische Sprache in slawischer Nachbarschaft', w:['Es hat zwei gleichberechtigte Amtssprachen','Seine Sprache ist mit Ungarisch verwandt'] } }
];

/* Lehrkräfte, die hier moderieren */
const LEHRKRAEFTE = [
  { name:'Frau Kowalski', fach:'Geschichte & Politik', land:'pl', ort:'Krakau',
    kurz:'Stellt die Aufgaben zu Erinnerungskultur und liest jede Einreichung zweimal.',
    hallo:'Schön, dass du da bist. Ich betreue hier die Aufgaben zu Geschichte und Politik — wenn etwas unklar ist, frag einfach.' },
  { name:'Herr Lindqvist', fach:'Erdkunde', land:'se', ort:'Göteborg',
    kurz:'Zuständig für alles, was mit Karten, Klima und Wegen zu tun hat.',
    hallo:'Hallo! Ich sehe, du warst schon auf der Karte unterwegs. Sag Bescheid, wenn du eine Aufgabe zu einem bestimmten Land brauchst.' },
  { name:'Mme Rousseau', fach:'Französisch & Europakunde', land:'fr', ort:'Lyon',
    kurz:'Achtet darauf, dass Beiträge in mehreren Sprachen willkommen sind.',
    hallo:'Bonjour! Du darfst deine Beiträge übrigens auch auf Französisch einreichen — oder in jeder anderen Sprache.' },
  { name:'Sr. Delgado', fach:'Spanisch & Medien', land:'es', ort:'Valencia',
    kurz:'Prüft Fotos und Videos und erklärt gern, warum etwas nicht freigegeben wurde.',
    hallo:'Hola! Wenn ein Beitrag abgelehnt wird, steht immer eine Begründung dabei. Das ist mir wichtig.' }
];

/* Aufgaben, die zu Beginn schon eingestellt sind */
const START_AUFGABEN = [
  { id:'t-schulweg', land:null, titel:'Dein Schulweg in drei Bildern',
    text:'Fotografiere drei Stationen deines Schulwegs und schreib je einen Satz dazu. Kein Gesicht muss darauf sein.',
    punkte:5, von:'Herr Lindqvist' },
  { id:'t-unwort', land:null, titel:'Ein Wort, das man nicht übersetzen kann',
    text:'Such ein Wort aus deiner Sprache, für das es im Deutschen oder Englischen keine Entsprechung gibt. Erklär, wann man es benutzt.',
    punkte:5, von:'Mme Rousseau' },
  { id:'t-debatte', land:null, titel:'Worüber bei euch gerade gestritten wird',
    text:'Nenne ein Thema, das in deinem Land öffentlich diskutiert wird, und beschreib beide Seiten in je drei Sätzen — ohne zu bewerten.',
    punkte:8, von:'Frau Kowalski' },
  { id:'t-lied', land:null, titel:'Ein Lied aus deinem Land',
    text:'Empfiehl ein Lied, das gerade bei Gleichaltrigen läuft. Was steht im Text, und warum funktioniert es?',
    punkte:4, von:'Sr. Delgado' },
  { id:'t-erinnerung', land:'pl', titel:'Ein Ort, an dem Geschichte sichtbar ist',
    text:'Such in deiner Stadt einen Ort, an dem etwas Vergangenes noch zu sehen ist — eine Lücke, eine Tafel, eine Narbe im Gebäude. Beschreib ihn.',
    punkte:8, von:'Frau Kowalski' },
  { id:'t-grenze', land:'de', titel:'Neun Nachbarn',
    text:'Deutschland grenzt an neun Länder. Wähl eines aus und finde heraus, was diese Grenze für Leute in deinem Alter praktisch bedeutet.',
    punkte:6, von:'Herr Lindqvist' }
];

/* ---- Kartendaten: unverändert aus dem Spiel ---- */

const MAP_CHARS = {
  I:'is', J:'ie', U:'uk', P:'pt', E:'es', F:'fr', B:'be', N:'nl',
  D:'de', K:'dk', V:'no', S:'se', M:'fi', T:'ee', L:'lv', Y:'lt',
  W:'pl', C:'cz', A:'at', Z:'ch', X:'it', H:'hu', Q:'hr', R:'ro', G:'gr'
};

const EUROPE_MAP = [
  '.......................................................VVVVVVVVVVV..........................',
  '................................................VVVVVVVVVVVVVVVVVVVVVV......................',
  '........IIIII..................................VVVVVVVVVVVVVVVVVMMVVV.......................',
  '....IIIIIIIIII...............................VVVVVVVVVVVVVVVMMMMMMMVV.......................',
  '....IIIIIIIIIII.............................VVVVVVVVVVVVVMMMMMMMMMMM........................',
  '.....IIIIIIIIII............................VVVVVVVVVVVVMMMMMMMMMMMMMM.......................',
  '.....IIIIIIIII............................VVVVVVVVVSV...MMMMMMMMMMMMMM......................',
  '........IIIII.............UU..............VVVVVVVSSSS....MMMMMMMMMMMM.......................',
  '........................UUUU..............VVVVVSSSSSSS...MMMMMMMMMMMM.......................',
  '.......................UUUUU.............VVVVVSSSSSSSSS..MMMMMMMMMMMM.......................',
  '.......................UUUUUU............VVVVVSSSSSSSSS..MMMMMMMMMMM........................',
  '......................UUUUUUU............VVVVVSSSSSSSSS...MMMMMMMMMM........................',
  '......................UUUUUUU...........VVVVVVSSSSSSSS....MMMMMMMMM.........................',
  '.......................UUUUUUU..........VVVVVVSSSSSSSS....MMMMMMMM..........................',
  '.......................UUUUUUU..........VVVVVVSSSSSSSS.....MMMMMM...........................',
  '........................UUUUUUU..........VVVVVSSSSSSSS......MMMM............................',
  '.................JJJ....UUUUUUUU.........VVVV.SSSSSSSS.......MM.............................',
  '...............JJJJJ.....UUUUUUU..............SSSSSSS.............................____......',
  '...............JJJJJJ....UUUUUUU..........KKK..SSSSSS.....................____________......',
  '..............JJJJJJJ...UUUUUUUU..........KKK..SSSSSS.................._______________......',
  '..............JJJJJJ....UUUUUUUU..........KKK..SSSSS...........TTTTTTT._______________......',
  '...............JJJJ.....UUUUUUUU.........KKKK...SSSS...........TTTTTTT._______________......',
  '.................J.....UUUUUUUUU.........KKKK..................TTTTTTT._______________......',
  '.......................UUUUUUUU..........KKKK.........................._______________......',
  '........................UUUUU.............DDDDDDDDD...........LLLLLLLLL_______________......',
  '..........................UU...........NNNDDDDDDDDDD..........LLLLLLLLL_______________......',
  '.......................................NNNDDDDDDDDDDWWWWWWWWWWWLLLLLLLL_______________......',
  '.......................................NNNDDDDDDDDDDDWWWWWWWWWW_______________________......',
  '........................................NNDDDDDDDDDDDWWWWWWWWWWYYYYYY_________________......',
  '........................................NNDDDDDDDDDDDWWWWWWWWWWWYYYY__________________......',
  '...................................FFBBBBBDDDDDDDDDDDWWWWWWWWWWWYYYY__________________......',
  '.................................FFFFFFBBDDDDDDDDDDDDWWWWWWWWWWW______________________......',
  '..............................FFFFFFFFFFFFDDDDDDDDDDDWWWWWWWWWW_______________________......',
  '............................FFFFFFFFFFFFFFFDDDDDDDDDDWWWWWWWWWW_______________________......',
  '..........................FFFFFFFFFFFFFFFFFDDDDDDDDDDWWWWWWWWWW_______________________......',
  '.........................FFFFFFFFFFFFFFFFFFDDDDDDDDDDWWWWWWWWW________________________......',
  '........................FFFFFFFFFFFFFFFFFFFDDDDDDDCCCCCWW_____________________________......',
  '........................FFFFFFFFFFFFFFFFFFFFDDCCCCCCCCCC______________________________......',
  '........................FFFFFFFFFFFFFFFFFFFF_DCCCCCCCCCC______________________________......',
  '........................FFFFFFFFFFFFFFFFFFFF__CCCCCCCCCCC____________RRRRRR___________......',
  '........................FFFFFFFFFFFFFFFFFFFF__CCCCCCCCCC________RRRRRRRRRRRR__________......',
  '.........................FFFFFFFFFFFFFFFFFF______CCCC_______HHHHRRRRRRRRRRRR__________......',
  '.........................FFFFFFFFFFFFFFFFFF_______AAAAA_HHHHHHHHRRRRRRRRRRRR________........',
  '.........................FFFFFFFFFFFFFFFFZZZ_AAAAAAAAAAAHHHHHHHHRRRRRRRRRRRRR___............',
  '..........................FFFFFFFFFFFFFZZZZZ_AAAAAAAAAAAAHHHHHHHRRRRRRRRRRRR................',
  '...........................FFFFFFFFFFFFZZZZZZAAAAAAAAAA__HHHH___RRRRRRRRRRR.................',
  '.............................FFFFFFFFFFZZZZZZ__XXXXX...QQQQQQ_____RRRRRRRR..................',
  '...........................EEEEEFFF........XXXXXXXXXX..QQQQQQQ________RRR_..................',
  '..................EEEEEEEEEEEEEEE..........XXXXXXXXXXX.QQQQQQQQ____________.................',
  '..............EPPEEEEEEEEEEEEEEEEE..........XXXXXXXXXX.QQQQQQQQQ___________.................',
  '..............PPPEEEEEEEEEEEEEEEE...........XXXXXXXXX...QQQQQQQ____________.................',
  '..............PPPEEEEEEEEEEEEEEEE...............XXXXXX...QQQQ_______________................',
  '..............PPPEEEEEEEEEEEEEEEE..............XXXXXXX....QQ________________................',
  '..............PPPEEEEEEEEEEEEEEE...............XXXXXXX.....________________.................',
  '..............PPPEEEEEEEEEEEEEEE................XXXXXXX.....______________..................',
  '..............PPPEEEEEEEEEEEEEEE..................XXXXX......____________...................',
  '.............PPPPEEEEEEEEEEEEEE....................XXXXX......___________...................',
  '.............PPPPEEEEEEEEEEEEE......................XXXXX......_GGGGGG__....................',
  '.............PPPPEEEEEEEEEEEE........................XXXXX......GGGGGGG.....................',
  '.............PPPPEEEEEEEEEEE.........................XXXXXX.....GGGGGGGG....................',
  '.............PPPPEEEEEEEEEE...........................XXXXXXX...GGGGGGG.....................',
  '.............PPPP.EEEEEEEE............................XXXXXXX...GGGGGG......................',
  '..................EEEE.................................XXXXX....GGGGG.......................',
  '........................................................X.......GGGG........................',
  '......................................................X........GGGGGG.......................',
  '.....................................................XX........GGGGGG.......................',
  '................................................XXXXXX.........GGGGGG.......................',
  '...............................................XXXXXX..........GGGGGGG......................',
  '..................................................XXX...........GGGGG.......................',
  '.................................................................GG.........................'
];

/* Fährverbindungen zu den Inseln – aus dem Spiel übernommen */
const FAEHREN = [['uk','fr'], ['ie','uk'], ['is','uk'], ['dk','se'], ['fi','ee']];

/* ---- Wortfilter: unverändert aus dem Spiel ---- */

const BAD_SUBSTRINGS = [
  'fick','fotze','hurensohn','hurentochter','wichs','arschloch',
  'schlampe','missgeburt','schwuchtel','drecksau','kackbratze',
  'penis','vagina','pimmel','muschi','titten','porno','sperma','dildo',
  'fuck','bitch','asshole','motherfucker','wanker','dickhead',
  'nigger','neger','kanake','judensau','faggot',
  'hitler','nazi','siegheil','hakenkreuz','swastika','holocaustleugn'
];

const BAD_WORDS = [
  'arsch','sex','sexy','hure','nutte','spast','spasti',
  'idiot','depp','fettsack','opfa',
  'ass','cunt','slut','whore','hoe','retard',
  'heil','sieg'
];

const BAD_NAMES = ['adolf','stalin','satan','putin','osama','admin','moderator'];

const LEHRER_PIN = '2468';

const INTERESSEN = ['Musik','Sport','Politik','Kunst','Programmieren','Klima','Kochen','Film',
  'Lesen','Fotografie','Reisen','Sprachen','Gaming','Theater','Wissenschaft','Ehrenamt'];

const STIFTE = [
  { id:'blau',   hex:'#2f4f8f', name:'Blau' },
  { id:'rot',    hex:'#cf4a37', name:'Rot' },
  { id:'gruen',  hex:'#2f7a4f', name:'Grün' },
  { id:'violett',hex:'#6b4c9a', name:'Violett' },
  { id:'ocker',  hex:'#b07d20', name:'Ocker' },
  { id:'tuerkis',hex:'#12796f', name:'Türkis' }
];
</script>
